<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria [
        <!ELEMENT libreria (libro+)>
        <!ELEMENT libro (titulo, autor+, categoria*, lenguaje?, anyo?, edicion?, precio)>
        <!ATTLIST libro ISBN CDATA #REQUIRED>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT categoria (#PCDATA)>
        <!ELEMENT lenguaje (#PCDATA)>
        <!ELEMENT anyo (#PCDATA)>
        <!ELEMENT edicion (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        ]>
<libreria>
  <libro ISBN="0123456001">
    <titulo>AAD1</titulo>
    <autor>Profesor 1</autor>
    <categoria>Programación</categoria>
    <anyo>2009</anyo>
    <edicion>7</edicion>
    <precio>19.99</precio>
  </libro>
  <libro ISBN="0123456002">
    <titulo>AAD2</titulo>
    <autor>Profesor 1</autor>
    <categoria>Programación</categoria>
    <anyo>2008</anyo>
    <precio>25.99</precio>
  </libro>
  <libro ISBN="0123456010">
    <titulo>SEGA</titulo>
    <autor>Yu Suzuki</autor>
    <autor>Yuji Naka</autor>
    <autor>Yuzo Koshiro</autor>
    <categoria>Videojuegos</categoria>
    <categoria>Ocio</categoria>
    <lenguaje>Japonés</lenguaje>
    <anyo>1999</anyo>
    <edicion>1</edicion>
    <precio>49.99</precio>
  </libro>
</libreria>